name = "rateme"
main = "src/worker.js"
compatibility_date = "2026-01-20"

[durable_objects]
bindings = [
  { name = "MY_DURABLE_OBJECT", class_name = "MyDurableObject" }
]

[[migrations]]
tag = "v1"
new_classes = ["MyDurableObject"]

[[kv_namespaces]]
binding = "USERS_KV"
id = "906909ed37a64c3c95b7c4b1fb8c3fb5"

[[kv_namespaces]]
binding = "BUSINESSES_KV"
id = "c647287b510243d795ad99144be8b9a9"